name: Build and Deploy Conductor to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_ID: i-0f3825346d84a197a

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::867344440197:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2 via SSM
        run: |
          COMMANDS_JSON=$(cat <<EOF
          {
            "commands": [
              "#!/bin/bash",
              "set -e",
              "echo '--- PRODUCTION DEPLOYMENT WITH OFFICIAL IMAGES ---'",
              
              "echo '--- Stopping and removing old containers ---'",
              "docker stop conductor-server conductor-ui redis elasticsearch mongo schellar nats nats-streaming || true",
              "docker rm conductor-server conductor-ui redis elasticsearch mongo schellar nats nats-streaming || true",

              "echo '--- Cleaning up Docker system to free up space ---'",
              "docker system prune -af",

              "echo '--- Removing old Docker network ---'",
              "docker network rm conductor-dev-net || true",

              "echo '--- Creating Docker network ---'",
              "docker network create conductor-dev-net",

              "echo '--- Starting Redis container (Primary DB + Queue) ---'",
              "docker run -d --name redis --network conductor-dev-net -p 6379:6379 --restart always -v redis-data:/data redis:6.2-alpine redis-server --save 20 1 --loglevel warning",

              "echo '--- Starting Elasticsearch container (Search/Indexing) ---'",
              "docker run -d --name elasticsearch --network conductor-dev-net --network-alias es -p 9200:9200 -p 9300:9300 -e 'ES_JAVA_OPTS=-Xms512m -Xmx1024m' -e 'transport.host=0.0.0.0' -e 'discovery.type=single-node' -e 'xpack.security.enabled=false' -v elasticsearch-data:/usr/share/elasticsearch/data --restart always elasticsearch:7.17.9",
              
              "echo '--- Starting MongoDB container (For Schellar only) ---'",
              "docker run -d --name mongo --network conductor-dev-net -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=root -v mongo-data:/data/db --restart always mongo:4.1.10",

              "echo '--- Starting NATS container ---'",
              "docker run -d --name nats --network conductor-dev-net -p 4222:4222 -p 8222:8222 --restart always nats:latest -js --http_port 8222",

              "echo '--- Starting NATS Streaming container ---'",
              "docker run -d --name nats-streaming --network conductor-dev-net -p 4223:4222 -p 8223:8222 --restart always nats-streaming:latest",

              "echo '--- Waiting for services to be ready ---'",
              "sleep 30",

              "echo '--- Starting Conductor Server (Official Image) ---'",
              "docker run -d --name conductor-server --network conductor-dev-net -p 8080:8080 --restart always -e CONFIG_PROP=config-local.properties -e ES_VERSION=7 -e INDEXING_ENABLED=true -e JAVA_OPTS='-Dpolyglot.engine.WarnInterpreterOnly=false' niemen/conductor-server:7.2.2",

              "echo '--- Starting Schellar container ---'",
              "docker run -d --name schellar --network conductor-dev-net -p 3001:3000 -e CONDUCTOR_API_URL=http://conductor-server:8080/api -e MONGO_ADDRESS=mongo -e MONGO_USERNAME=root -e MONGO_PASSWORD=root --restart always flaviostutz/schellar",

              "echo '--- Starting Conductor UI (Official Image) ---'",
              "docker run -d --name conductor-ui --network conductor-dev-net -p 5000:5000 -e WF_SERVER=http://conductor-server:8080 --restart always niemen/conductor-ui:4.0.1",

              "echo '--- PRODUCTION DEPLOYMENT COMPLETED SUCCESSFULLY ---'"
            ]
          }
          EOF
          )

          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "PRODUCTION Deployment with Official Images - Commit: ${{ github.sha }}" \
            --targets "Key=InstanceIds,Values=${{ env.EC2_INSTANCE_ID }}" \
            --parameters "$COMMANDS_JSON" \
            --region ${{ env.AWS_REGION }} \
            --query "Command.CommandId" \
            --output text)

          echo "Waiting for PRODUCTION deployment to complete..."
          while true; do
            STATUS=$(aws ssm list-command-invocations \
              --command-id "$COMMAND_ID" \
              --instance-id "${{ env.EC2_INSTANCE_ID }}" \
              --region ${{ env.AWS_REGION }} \
              --query 'CommandInvocations[0].Status' \
              --output text)
            echo "PRODUCTION deployment status: $STATUS"

            if [[ "$STATUS" == "Success" ]]; then
              echo "✅ PRODUCTION DEPLOYMENT COMPLETED SUCCESSFULLY!"
              break
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
              echo "❌ PRODUCTION DEPLOYMENT FAILED with status: $STATUS"
              aws ssm get-command-invocation \
                --command-id "$COMMAND_ID" \
                --instance-id "${{ env.EC2_INSTANCE_ID }}" \
                --query "StandardErrorContent" \
                --output text
              exit 1
            fi
            sleep 15
          done
